//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameRigWebSite_Project.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/GameRigService")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int activeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phonenumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usertypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int active {
            get {
                return this.activeField;
            }
            set {
                if ((this.activeField.Equals(value) != true)) {
                    this.activeField = value;
                    this.RaisePropertyChanged("active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastnameField, value) != true)) {
                    this.lastnameField = value;
                    this.RaisePropertyChanged("lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phonenumber {
            get {
                return this.phonenumberField;
            }
            set {
                if ((object.ReferenceEquals(this.phonenumberField, value) != true)) {
                    this.phonenumberField = value;
                    this.RaisePropertyChanged("phonenumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usertype {
            get {
                return this.usertypeField;
            }
            set {
                if ((object.ReferenceEquals(this.usertypeField, value) != true)) {
                    this.usertypeField = value;
                    this.RaisePropertyChanged("usertype");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewsLetter", Namespace="http://schemas.datacontract.org/2004/07/GameRigService")]
    [System.SerializableAttribute()]
    public partial class NewsLetter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAd {
            get {
                return this.EmailAdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAdField, value) != true)) {
                    this.EmailAdField = value;
                    this.RaisePropertyChanged("EmailAd");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddProduct", Namespace="http://schemas.datacontract.org/2004/07/GameRigService")]
    [System.SerializableAttribute()]
    public partial class AddProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imgurlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Col {
            get {
                return this.ColField;
            }
            set {
                if ((object.ReferenceEquals(this.ColField, value) != true)) {
                    this.ColField = value;
                    this.RaisePropertyChanged("Col");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Quant {
            get {
                return this.QuantField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantField, value) != true)) {
                    this.QuantField = value;
                    this.RaisePropertyChanged("Quant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desc {
            get {
                return this.descField;
            }
            set {
                if ((object.ReferenceEquals(this.descField, value) != true)) {
                    this.descField = value;
                    this.RaisePropertyChanged("desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imgurl {
            get {
                return this.imgurlField;
            }
            set {
                if ((object.ReferenceEquals(this.imgurlField, value) != true)) {
                    this.imgurlField = value;
                    this.RaisePropertyChanged("imgurl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductTable", Namespace="http://schemas.datacontract.org/2004/07/GameRigService")]
    [System.SerializableAttribute()]
    public partial class ProductTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImgUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GameRigWebSite_Project.ServiceReference1.InvoiceTable[] InvoiceTablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Colour {
            get {
                return this.ColourField;
            }
            set {
                if ((object.ReferenceEquals(this.ColourField, value) != true)) {
                    this.ColourField = value;
                    this.RaisePropertyChanged("Colour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desc {
            get {
                return this.DescField;
            }
            set {
                if ((object.ReferenceEquals(this.DescField, value) != true)) {
                    this.DescField = value;
                    this.RaisePropertyChanged("Desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImgUrl {
            get {
                return this.ImgUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImgUrlField, value) != true)) {
                    this.ImgUrlField = value;
                    this.RaisePropertyChanged("ImgUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GameRigWebSite_Project.ServiceReference1.InvoiceTable[] InvoiceTables {
            get {
                return this.InvoiceTablesField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceTablesField, value) != true)) {
                    this.InvoiceTablesField = value;
                    this.RaisePropertyChanged("InvoiceTables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantityField, value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceTable", Namespace="http://schemas.datacontract.org/2004/07/GameRigService")]
    [System.SerializableAttribute()]
    public partial class InvoiceTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GameRigWebSite_Project.ServiceReference1.ProductTable ProductTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GameRigWebSite_Project.ServiceReference1.UserTable UserTableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceId {
            get {
                return this.InvoiceIdField;
            }
            set {
                if ((this.InvoiceIdField.Equals(value) != true)) {
                    this.InvoiceIdField = value;
                    this.RaisePropertyChanged("InvoiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GameRigWebSite_Project.ServiceReference1.ProductTable ProductTable {
            get {
                return this.ProductTableField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductTableField, value) != true)) {
                    this.ProductTableField = value;
                    this.RaisePropertyChanged("ProductTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GameRigWebSite_Project.ServiceReference1.UserTable UserTable {
            get {
                return this.UserTableField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTableField, value) != true)) {
                    this.UserTableField = value;
                    this.RaisePropertyChanged("UserTable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserTable", Namespace="http://schemas.datacontract.org/2004/07/GameRigService")]
    [System.SerializableAttribute()]
    public partial class UserTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GameRigWebSite_Project.ServiceReference1.InvoiceTable[] InvoiceTablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsertypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int activeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellNumber {
            get {
                return this.CellNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CellNumberField, value) != true)) {
                    this.CellNumberField = value;
                    this.RaisePropertyChanged("CellNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAd {
            get {
                return this.EmailAdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAdField, value) != true)) {
                    this.EmailAdField = value;
                    this.RaisePropertyChanged("EmailAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GameRigWebSite_Project.ServiceReference1.InvoiceTable[] InvoiceTables {
            get {
                return this.InvoiceTablesField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceTablesField, value) != true)) {
                    this.InvoiceTablesField = value;
                    this.RaisePropertyChanged("InvoiceTables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usertype {
            get {
                return this.UsertypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UsertypeField, value) != true)) {
                    this.UsertypeField = value;
                    this.RaisePropertyChanged("Usertype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int active {
            get {
                return this.activeField;
            }
            set {
                if ((this.activeField.Equals(value) != true)) {
                    this.activeField = value;
                    this.RaisePropertyChanged("active");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService2")]
    public interface IService2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/AddMember", ReplyAction="http://tempuri.org/IService2/AddMemberResponse")]
        int AddMember(GameRigWebSite_Project.ServiceReference1.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/AddMember", ReplyAction="http://tempuri.org/IService2/AddMemberResponse")]
        System.Threading.Tasks.Task<int> AddMemberAsync(GameRigWebSite_Project.ServiceReference1.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getProId", ReplyAction="http://tempuri.org/IService2/getProIdResponse")]
        int getProId(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getProId", ReplyAction="http://tempuri.org/IService2/getProIdResponse")]
        System.Threading.Tasks.Task<int> getProIdAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/AddSubscriber", ReplyAction="http://tempuri.org/IService2/AddSubscriberResponse")]
        int AddSubscriber(GameRigWebSite_Project.ServiceReference1.NewsLetter Nlet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/AddSubscriber", ReplyAction="http://tempuri.org/IService2/AddSubscriberResponse")]
        System.Threading.Tasks.Task<int> AddSubscriberAsync(GameRigWebSite_Project.ServiceReference1.NewsLetter Nlet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Login", ReplyAction="http://tempuri.org/IService2/LoginResponse")]
        int Login(string EmailS, string PassWordS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Login", ReplyAction="http://tempuri.org/IService2/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(string EmailS, string PassWordS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/AddNewProduct", ReplyAction="http://tempuri.org/IService2/AddNewProductResponse")]
        int AddNewProduct(string ProductName, int ProductPrice, string Colour, string Quantity, string type, string Description, string image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/AddNewProduct", ReplyAction="http://tempuri.org/IService2/AddNewProductResponse")]
        System.Threading.Tasks.Task<int> AddNewProductAsync(string ProductName, int ProductPrice, string Colour, string Quantity, string type, string Description, string image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/SearchProduct", ReplyAction="http://tempuri.org/IService2/SearchProductResponse")]
        int SearchProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/SearchProduct", ReplyAction="http://tempuri.org/IService2/SearchProductResponse")]
        System.Threading.Tasks.Task<int> SearchProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/EditProduct", ReplyAction="http://tempuri.org/IService2/EditProductResponse")]
        bool EditProduct(GameRigWebSite_Project.ServiceReference1.AddProduct add, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/EditProduct", ReplyAction="http://tempuri.org/IService2/EditProductResponse")]
        System.Threading.Tasks.Task<bool> EditProductAsync(GameRigWebSite_Project.ServiceReference1.AddProduct add, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/DeleteProduct", ReplyAction="http://tempuri.org/IService2/DeleteProductResponse")]
        int DeleteProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/DeleteProduct", ReplyAction="http://tempuri.org/IService2/DeleteProductResponse")]
        System.Threading.Tasks.Task<int> DeleteProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/GetProduct", ReplyAction="http://tempuri.org/IService2/GetProductResponse")]
        GameRigWebSite_Project.ServiceReference1.AddProduct GetProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/GetProduct", ReplyAction="http://tempuri.org/IService2/GetProductResponse")]
        System.Threading.Tasks.Task<GameRigWebSite_Project.ServiceReference1.AddProduct> GetProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/DeleteUser", ReplyAction="http://tempuri.org/IService2/DeleteUserResponse")]
        int DeleteUser(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/DeleteUser", ReplyAction="http://tempuri.org/IService2/DeleteUserResponse")]
        System.Threading.Tasks.Task<int> DeleteUserAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/GetUser", ReplyAction="http://tempuri.org/IService2/GetUserResponse")]
        GameRigWebSite_Project.ServiceReference1.User GetUser(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/GetUser", ReplyAction="http://tempuri.org/IService2/GetUserResponse")]
        System.Threading.Tasks.Task<GameRigWebSite_Project.ServiceReference1.User> GetUserAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Registerd", ReplyAction="http://tempuri.org/IService2/RegisterdResponse")]
        bool Registerd(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Registerd", ReplyAction="http://tempuri.org/IService2/RegisterdResponse")]
        System.Threading.Tasks.Task<bool> RegisterdAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/searchProducts", ReplyAction="http://tempuri.org/IService2/searchProductsResponse")]
        GameRigWebSite_Project.ServiceReference1.ProductTable[] searchProducts(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/searchProducts", ReplyAction="http://tempuri.org/IService2/searchProductsResponse")]
        System.Threading.Tasks.Task<GameRigWebSite_Project.ServiceReference1.ProductTable[]> searchProductsAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getAllProducts", ReplyAction="http://tempuri.org/IService2/getAllProductsResponse")]
        GameRigWebSite_Project.ServiceReference1.ProductTable[] getAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getAllProducts", ReplyAction="http://tempuri.org/IService2/getAllProductsResponse")]
        System.Threading.Tasks.Task<GameRigWebSite_Project.ServiceReference1.ProductTable[]> getAllProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getAllFpProducts", ReplyAction="http://tempuri.org/IService2/getAllFpProductsResponse")]
        GameRigWebSite_Project.ServiceReference1.ProductTable[] getAllFpProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getAllFpProducts", ReplyAction="http://tempuri.org/IService2/getAllFpProductsResponse")]
        System.Threading.Tasks.Task<GameRigWebSite_Project.ServiceReference1.ProductTable[]> getAllFpProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getAllFnProducts", ReplyAction="http://tempuri.org/IService2/getAllFnProductsResponse")]
        GameRigWebSite_Project.ServiceReference1.ProductTable[] getAllFnProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getAllFnProducts", ReplyAction="http://tempuri.org/IService2/getAllFnProductsResponse")]
        System.Threading.Tasks.Task<GameRigWebSite_Project.ServiceReference1.ProductTable[]> getAllFnProductsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService2Channel : GameRigWebSite_Project.ServiceReference1.IService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2Client : System.ServiceModel.ClientBase<GameRigWebSite_Project.ServiceReference1.IService2>, GameRigWebSite_Project.ServiceReference1.IService2 {
        
        public Service2Client() {
        }
        
        public Service2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddMember(GameRigWebSite_Project.ServiceReference1.User u) {
            return base.Channel.AddMember(u);
        }
        
        public System.Threading.Tasks.Task<int> AddMemberAsync(GameRigWebSite_Project.ServiceReference1.User u) {
            return base.Channel.AddMemberAsync(u);
        }
        
        public int getProId(string name) {
            return base.Channel.getProId(name);
        }
        
        public System.Threading.Tasks.Task<int> getProIdAsync(string name) {
            return base.Channel.getProIdAsync(name);
        }
        
        public int AddSubscriber(GameRigWebSite_Project.ServiceReference1.NewsLetter Nlet) {
            return base.Channel.AddSubscriber(Nlet);
        }
        
        public System.Threading.Tasks.Task<int> AddSubscriberAsync(GameRigWebSite_Project.ServiceReference1.NewsLetter Nlet) {
            return base.Channel.AddSubscriberAsync(Nlet);
        }
        
        public int Login(string EmailS, string PassWordS) {
            return base.Channel.Login(EmailS, PassWordS);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string EmailS, string PassWordS) {
            return base.Channel.LoginAsync(EmailS, PassWordS);
        }
        
        public int AddNewProduct(string ProductName, int ProductPrice, string Colour, string Quantity, string type, string Description, string image) {
            return base.Channel.AddNewProduct(ProductName, ProductPrice, Colour, Quantity, type, Description, image);
        }
        
        public System.Threading.Tasks.Task<int> AddNewProductAsync(string ProductName, int ProductPrice, string Colour, string Quantity, string type, string Description, string image) {
            return base.Channel.AddNewProductAsync(ProductName, ProductPrice, Colour, Quantity, type, Description, image);
        }
        
        public int SearchProduct(int id) {
            return base.Channel.SearchProduct(id);
        }
        
        public System.Threading.Tasks.Task<int> SearchProductAsync(int id) {
            return base.Channel.SearchProductAsync(id);
        }
        
        public bool EditProduct(GameRigWebSite_Project.ServiceReference1.AddProduct add, int Id) {
            return base.Channel.EditProduct(add, Id);
        }
        
        public System.Threading.Tasks.Task<bool> EditProductAsync(GameRigWebSite_Project.ServiceReference1.AddProduct add, int Id) {
            return base.Channel.EditProductAsync(add, Id);
        }
        
        public int DeleteProduct(int id) {
            return base.Channel.DeleteProduct(id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteProductAsync(int id) {
            return base.Channel.DeleteProductAsync(id);
        }
        
        public GameRigWebSite_Project.ServiceReference1.AddProduct GetProduct(int id) {
            return base.Channel.GetProduct(id);
        }
        
        public System.Threading.Tasks.Task<GameRigWebSite_Project.ServiceReference1.AddProduct> GetProductAsync(int id) {
            return base.Channel.GetProductAsync(id);
        }
        
        public int DeleteUser(string email) {
            return base.Channel.DeleteUser(email);
        }
        
        public System.Threading.Tasks.Task<int> DeleteUserAsync(string email) {
            return base.Channel.DeleteUserAsync(email);
        }
        
        public GameRigWebSite_Project.ServiceReference1.User GetUser(int ID) {
            return base.Channel.GetUser(ID);
        }
        
        public System.Threading.Tasks.Task<GameRigWebSite_Project.ServiceReference1.User> GetUserAsync(int ID) {
            return base.Channel.GetUserAsync(ID);
        }
        
        public bool Registerd(string email, string password) {
            return base.Channel.Registerd(email, password);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterdAsync(string email, string password) {
            return base.Channel.RegisterdAsync(email, password);
        }
        
        public GameRigWebSite_Project.ServiceReference1.ProductTable[] searchProducts(string name) {
            return base.Channel.searchProducts(name);
        }
        
        public System.Threading.Tasks.Task<GameRigWebSite_Project.ServiceReference1.ProductTable[]> searchProductsAsync(string name) {
            return base.Channel.searchProductsAsync(name);
        }
        
        public GameRigWebSite_Project.ServiceReference1.ProductTable[] getAllProducts() {
            return base.Channel.getAllProducts();
        }
        
        public System.Threading.Tasks.Task<GameRigWebSite_Project.ServiceReference1.ProductTable[]> getAllProductsAsync() {
            return base.Channel.getAllProductsAsync();
        }
        
        public GameRigWebSite_Project.ServiceReference1.ProductTable[] getAllFpProducts() {
            return base.Channel.getAllFpProducts();
        }
        
        public System.Threading.Tasks.Task<GameRigWebSite_Project.ServiceReference1.ProductTable[]> getAllFpProductsAsync() {
            return base.Channel.getAllFpProductsAsync();
        }
        
        public GameRigWebSite_Project.ServiceReference1.ProductTable[] getAllFnProducts() {
            return base.Channel.getAllFnProducts();
        }
        
        public System.Threading.Tasks.Task<GameRigWebSite_Project.ServiceReference1.ProductTable[]> getAllFnProductsAsync() {
            return base.Channel.getAllFnProductsAsync();
        }
    }
}
